### ISSUE TITLE
Little fix for dde-dock right click

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/dde-dock#31] opened 2017-01-11 06:41 UTC
If make a right click in dde-dock pop up show options for make permanently in bar or remove, but if application name not very large, options not complete show.

Maybe use minimal width more larger for pop up fix this.

Please see example in image, system language is Brazilian Portuguese:

![image](https://cloud.githubusercontent.com/assets/6098501/21838267/2eedbb6e-d7b8-11e6-9168-e3fbe13c7a84.png)

**Comment by sbwtw** [comment] 2017-01-11 13:51
@hualet

**Comment by hualet** [comment] 2017-01-12 01:03
Hi @bigbruno , I tested it on my deepin box, didn't reproduce the problem.

![deepinscreenshot20170112085550](https://cloud.githubusercontent.com/assets/2023967/21872757/05c4a6bc-d830-11e6-9102-c07706d28d86.png)

Or maybe the problem is solved somehow by dropping the navigation key(the letter with underline mark), hopefully it will get an update soon. Please help us test it then.

**Comment by hualet** [comment] 2017-01-12 04:45
@bigbruno I think you've confirmed that the deb I gave you solved the problem you've metioned, so I'll close this issue. If later updates still don't solve this, we'll reopen this issue.

In case someone other encounter this, the problem solver deb is attached :smiley: 
[deepin-menu.zip](https://github.com/linuxdeepin/dde-dock/files/700696/deepin-menu.zip)

**Closed by hualet** 2017-01-12 04:45 UTC
